// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fumbjxfcofoczbksfrio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1bWJqeGZjb2ZvY3pia3NmcmlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDg2MjEsImV4cCI6MjA2NjQyNDYyMX0.xOXTGzHsUu2fK88LruEAswbNZJRihGvzUHzUREMRBSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);